hello out there ^^this points to yahoo->http://www.yahoo.com^^ more text

This is bullets:
.bullet first
.bullet second
.bullet third
.bullet fourth
after bullets

NUmbered list:
.list AAAAA
.list BBBBB
.list CCCC
after list

and this points to ^^google->http://www.google.com^^
.chapter blah  blah  blah  blah 
.author blah  blah  blah 

.x  ["Hello world #{Date.new}"]

Surprise. blah  blah  blah  blah  blah  blah  blah 
.x inc('test.rb')
blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah , blah  blah  blah  blah  blah  blah  blah . blah  blah  blah  blah  blah  blah  blah , blah  blah , blah 's blah  blah  blah  blah  blah 's blah  blah , blah 's blah  blah  blah , blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah .

