.chapter blah  blah  blah  blah 
.author blah  blah  blah 

Surprise. blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah , blah  blah  blah  blah  blah  blah  blah . blah  blah  blah  blah  blah  blah  blah , blah  blah , blah 's blah  blah  blah  blah  blah 's blah  blah , blah 's blah  blah  blah , blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah .

.code
a = 44
b = 99
a.times do |i|
  puts i
end
.body

It's blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
much blah  blah  blah  blah  blah  blah  blah  blah  blah .
All blah  blah  blah  blah  blah  blah , blah  blah 
the blah  blah  blah  blah  blah  blah  blah  blah 
in blah  blah  blah  blah  blah  blah 1970s, blah .

.section blah  blah  blah  blah  blah 

If blah  blah 1970s blah  blah  blah  blah  blah  blah  blah , blah  blah 
for blah  blah , blah  blah  blah  blah  blah , blah  blah  blah 
of blah  blah  blah , blah  blah  blah  blah  blah  blah  blah 60s
and blah  blah  blah , blah  blah  blah  blah 
and blah , blah  blah  blah  blah  blah .

The blah  blah  blah -Johan blah  blah  blah  blah ,
and blah  blah  blah  blah  blah  blah 
event blah . blah  blah 's blah  blah  blah  blah ?
That's blah  blah  blah  blah  blah : blah  blah 
the blah  blah  blah  blah  blah  blah  blah 
and blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
the blah  blah  blah  blah  blah  blah  blah  blah .
So blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 14th blah  blah 
exactly blah 5:01:00 blah  blah  blah  blah  blah  blah . blah  blah  blah 
like blah  blah  blah , blah  blah  blah  blah 57 blah  blah , blah 
northwest blah  blah  blah  blah  blah , blah 
5:01:58 blah , blah  blah  blah . blah  blah  blah  blah  blah  blah  blah 
the blah  blah ? blah  blah  blah  blah  blah  blah  blah -- blah  blah 
too blah -- blah  blah  blah  blah  blah , blah  blah  blah  blah  blah 
and blah  blah  blah . blah  blah  blah  blah  blah  blah  blah 
situation blah  blah  blah  blah  blah  blah  blah  blah  blah  blah , blah 
each blah  blah  blah  blah  blah  blah  blah : blah  blah  blah 
DOWN blah  blah  blah  blah  blah  blah  blah , blah  blah  blah 
moving blah  blah  blah  blah  blah  blah . blah  blah  blah  blah  blah 
computer blah  blah  blah  blah  blah  blah "things blah 
in blah " blah  blah  blah  blah  blah  blah  blah  blah  blah  blah .

Our blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
building blah  blah  blah  blah  blah  blah  blah  blah 
the blah  blah  blah  blah  blah  blah  blah . blah  blah 
of blah  blah  blah  blah  blah  blah  blah  blah  blah 
and blah  blah  blah  blah  blah  blah  blah  blah 
functions blah  blah . blah  blah  blah  blah  blah  blah  blah 
complex blah  blah  blah  blah  blah . blah  blah  blah 
very, blah  blah  blah  blah  blah  blah  blah  blah  blah 
record blah  blah  blah  blah  blah  blah  blah  blah .
That's blah .

.section blah  blah 

If blah  blah  blah  blah  blah  blah  blah 
up blah  blah  blah  blah  blah  blah  blah  blah 
or blah  blah  blah  blah  blah , blah  blah 
a blah  blah  blah  blah  blah  blah  blah  blah  blah .
Think blah  blah : blah  blah  blah  blah  blah  blah  blah 
separate blah ~~things~~, blah  blah  blah  blah  blah  blah .
In blah  blah  blah  blah  blah  blah  blah  blah 
the blah  blah  blah  blah  blah  blah  blah -pushing blah .

Unfortunately blah  blah  blah  blah , blah  blah  blah  blah 
their blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
things blah : blah  blah  blah  blah  blah  blah  blah  blah  blah 
in blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 'is blah  blah  blah '
and blah 'is blah  blah  blah ' blah  blah . blah  blah  blah  blah  blah 
tended blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah .

** blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah (maybe)

So blah  blah  blah {{According blah  blah  blah ~~Olsen~~,
Norwegians blah , blah  blah , blah 
be blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
of blah . blah  blah  blah  blah  blah  blah  blah  blah  blah  blah .}}
set blah  blah  blah  blah  blah 
that blah  blah  blah  blah  blah  blah  blah  blah  blah 
the blah . blah  blah  blah  blah  blah  blah  blah  blah 
define blah  blah  blah  blah -- blah  blah  blah  blah  blah  blah  blah --
in blah  blah  blah  blah . blah  blah  blah , blah "Here blah  blah  blah 
code blah  blah  blah  blah  blah  blah  blah  blah . blah  blah  blah  blah 
code blah  blah  blah  blah  blah  blah ."

Dahl blah  blah  blah  blah  blah  blah  blah  blah  blah 
things blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
like blah  blah  blah  blah  blah  blah  blah  blah  blah .
If blah  blah  blah  blah  blah  blah  blah  blah  blah  blah :
Dahl blah  blah  blah  blah  blah  blah ~~objects~~ blah  blah  blah 
~~classes~~. blah  blah , blah ,
was blah  blah  blah  blah  blah  blah  blah  blah 
just blah  blah  blah  blah  blah  blah  blah : blah  blah ,
plus blah  blah  blah  blah  blah  blah  blah  blah , blah  blah  blah 
to blah  blah  blah  blah  blah :

*** blah  blah  blah  blah  blah , blah 

As blah  blah  blah  blah  blah  blah  blah  blah  blah  blah ,
Dahl blah  blah  blah 't blah  blah  blah  blah  blah ,
they blah  blah  blah  blah  blah  blah  blah  blah  blah 
overriden blah  blah  blah  blah  blah  blah .

Dahl blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
programmers blah  blah  blah  blah . blah  blah  blah  blah 
solve blah  blah  blah , blah  blah ,
and blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
they blah  blah  blah  blah  blah : blah  blah 
out blah  blah  blah  blah  blah  blah  blah ~~things~~, blah 
from blah  blah  blah  blah  blah  blah 
classifications blah  blah  blah  blah  blah  blah .
Dahl blah  blah  blah  blah  blah  blah  blah 
Simula blah  blah 1967 blah ...

.section blah  blah  blah  blah 't blah  blah  blah  blah 

...nothing blah  blah . blah  blah  blah  blah  blah ,
representing blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
the blah , blah  blah  blah  blah  blah  blah  blah  blah  blah 
the blah  blah  blah  blah  blah  blah  blah  blah 
been blah  blah  blah . blah  blah  blah  blah  blah  blah  blah  blah  blah .
Certainly blah  blah  blah  blah . blah  blah  blah  blah  blah  blah  blah ,
but blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah .
Certainly blah  blah  blah  blah  blah  blah  blah  blah  blah -- blah  blah  blah --
languages blah  blah  blah .

So blah  blah 't blah  blah  blah  blah ? blah  blah  blah  blah  blah .
Questions blah  blah  blah  blah  blah  blah  blah  blah ~~why~~ blah  blah  blah .
Still blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
of blah {{Well blah  blah  blah  blah  blah  blah  blah  blah , blah 
group blah , blah  blah , blah  blah  blah  blah  blah  blah  blah .}}
Was blah , blah  blah  blah , blah  blah ? blah  blah  blah  blah 1967 blah  blah  blah  blah 
general blah  blah  blah . blah , blah  blah  blah 
otherwise blah -- blah  blah  blah  blah  blah  blah .
It blah  blah  blah 't blah  blah  blah  blah  blah  blah  blah , blah  blah 
of blah  blah , blah  blah : blah  blah  blah  blah  blah  blah  blah  blah 
back blah . blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
but blah  blah , blah  blah  blah  blah . blah  blah  blah  blah  blah ,
location blah .

Whatever blah  blah , blah  blah  blah  blah  blah  blah  blah  blah 
did blah  blah  blah  blah  blah . blah , blah  blah , blah  blah ,
all blah  blah  blah  blah  blah  blah  blah  blah  blah , blah  blah 
ideas blah  blah  blah  blah  blah  blah  blah .

.section blah  blah 

### blah 's blah  blah 

Like blah  blah  blah  blah , blah  blah  blah 's blah  blah  blah  blah  blah  blah  blah -oriented blah . blah  blah , blah  blah  blah  blah  blah  blah "big blah " blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah , blah  blah  blah  blah  blah  blah  blah  blah . blah  blah  blah  blah  blah [^not-all-static] blah  blah  blah  blah  blah  blah -72 blah  blah  blah  blah  blah  blah  blah , blah , blah , blah , blah -compiling, blah , blah  blah . blah  blah , blah  blah  blah  blah  blah  blah  blah *agile* blah  blah  blah  blah  blah  blah  blah  blah .

Facilitating blah  blah  blah  blah  blah  blah  blah 's blah  blah  blah :

* blah  blah 
* blah -oriented blah 
* blah  blah  blah  blah 
* blah 
* blah -based blah 

As blah 'll blah  blah  blah  blah  blah  blah  blah , blah  blah  blah  blah  blah 's blah  blah  blah  blah  blah . blah  blah , blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah .

[^not-all-static]: blah  blah , blah  blah  blah  blah  blah  blah  blah  blah  blah  blah . blah  blah  blah , blah , blah , blah  blah 67 blah  blah  blah  blah  blah  blah  blah  blah  blah .

A blah  blah  blah  blah 
----------------------------

Although blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah , blah  blah ; blah 's blah  blah  blah  blah . blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah (Kay blah 1993) blah  blah . blah  blah , blah  blah  blah  blah :

 blah  blah * blah  blah (Sutherland blah 1964)
 blah  blah * blah "The blah  blah  blah  blah "
 blah  blah * blah  blah 220 blah  blah  blah 
 blah  blah * blah  blah  blah  blah  blah (Hewitt blah 1969)

I blah  blah  blah  blah  blah  blah  blah  blah  blah  blah , blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah : blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah . blah  blah 'll blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah . blah  blah , blah  blah  blah  blah  blah -oriented blah  blah  blah  blah  blah  blah  blah  blah  blah (or blah  blah  blah  blah  blah ):

 blah  blah  blah  blah  blah = blah  blah + blah  blah + blah  blah + blah ???

If blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 'll blah  blah  blah  blah  blah  blah  blah  blah  blah . blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah (PARC). blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah . blah  blah  blah , blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah ,[^sixth] blah  blah  blah  blah  blah  blah :

 blah  blah 1. blah  blah  blah  blah , blah  blah .
 blah  blah 2. blah  blah  blah  blah .
 blah  blah 3. blah  blah  blah .
 blah  blah 4. blah  blah  blah  blah  blah  blah  blah  blah .
 blah  blah 5. blah  blah  blah  blah  blah  blah  blah .

In blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah , blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah .

[^sixth]: blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah , blah  blah 'll blah  blah  blah  blah  blah  blah  blah .

### blah -72

The blah  blah  blah -72, blah  blah  blah  blah  blah  blah 4+ blah  blah  blah  blah , blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah -- blah  blah  blah , blah  blah  blah  blah `case` blah , blah  blah :

 blah  blah  blah  blah # blah  blah  blah _honking_switch.rb blah 

The blah  blah  blah  blah  blah `SwitchyMan` blah  blah  blah  blah  blah  blah  blah  blah `lambda` blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah . blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah -72 blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah .[^schemers]. blah  blah  blah  blah  blah  blah  blah  blah :

 blah  blah  blah  blah # blah  blah  blah _honking_switch.rb blah 
	
While blah  blah , blah 'll blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah , blah  blah  blah  blah . blah  blah , blah -72 blah  blah  blah  blah  blah . blah  blah , blah  blah  blah  blah  blah  blah  blah  blah  blah  blah ; blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah , blah  blah  blah  blah  blah  blah  blah  blah .

[^schemers]: blah  blah 've blah  blah  blah  blah  blah  blah  blah  blah  blah  blah , blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah .

### blah -76

The blah  blah  blah -72 blah  blah -76 blah  blah  blah  blah  blah  blah . blah  blah 

* blah -76
 blah  blah - blah  blah  blah  blah  blah  blah  blah 
 blah  blah - blah , blah  blah , blah  blah  blah  blah  blah  blah 
 blah  blah  blah  blah + blah 
 blah  blah  blah  blah + blah  blah  blah -72
 blah  blah - blah  blah  blah 
 blah  blah  blah  blah - blah 
 blah  blah  blah  blah  blah  blah + blah  blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 
 blah  blah  blah  blah  blah  blah + blah  blah 't blah  blah  blah  blah  blah  blah  blah 

### blah  blah 

 blah  blah - blah  blah  blah  blah 
 blah  blah  blah  blah + blah  blah 
 blah  blah - blah  blah  blah  blah  blah  blah  blah  blah 
 blah  blah - blah  blah 
 blah  blah  blah  blah - blah  blah 
 blah  blah  blah  blah - blah  blah 
 blah  blah  blah  blah - blah  blah  blah 

### blah -80

 blah  blah - blah  blah  blah  blah -76
 blah  blah - blah  blah  blah 
 blah  blah  blah  blah + blah  blah  blah -arrow blah  blah 
 blah  blah - blah  blah 
 blah  blah - blah  blah  blah  blah 
 blah  blah  blah  blah + blah 76 blah  blah  blah  blah  blah  blah  blah  blah  blah  blah 

### blah 

 blah  blah - blah  blah  blah  blah 
 blah  blah  blah  blah + blah  blah  blah  blah 68K blah 
 blah  blah - blah  blah  blah "Blue blah " blah  blah  blah 
 blah  blah - blah  blah 80
 blah  blah - blah  blah  blah ? blah 
 blah  blah  blah  blah + blah  blah 

