puts __FILE__

require "notroff/string_extensions"
require "notroff/text"
require "notroff/io"
require "notroff/filter"
require "notroff/code_scrubber"
require "notroff/embedded"
require "notroff/paragraph_joiner"
require "notroff/type_assigner"
require "notroff/processor"
require "notroff/command_processor"
require "notroff/composite_processor"
require "notroff/tokenize"
require "notroff/html_renderer"
require "notroff/docbook_renderer"
require "notroff/formatter"
require "notroff/filter"
