Verbose = false unless defined?(Verbose)

require "notroff/logger"
require "notroff/string_extensions"
require "notroff/text"
require "notroff/io"
require "notroff/filter"
require "notroff/code_scrubber"
require "notroff/embedded"
require "notroff/paragraph_joiner"
require "notroff/type_assigner"
require "notroff/processor"
require "notroff/command_processor"
require "notroff/composite_processor"
require "notroff/tokenize"
require "notroff/html_renderer"
require "notroff/docbook_renderer"
require "notroff/odt_renderer"
require "notroff/odt_replacer"
require "notroff/template_expander"
require "notroff/type_refiner"
require "notroff/filter"
require "notroff/grouper"
require "notroff/formatter"
